import SeerJSON.SeerDataType.SeerJSON;
import SeerJSON.SeerDataType.SeerStringifiedJSON;

public class App {
    
    public static void main(String[] args){

        final String string = "[\n"
	 + "  {\n"
	 + "	\"_test\": [1, 2, 3, 4]\",\n"
	 + "    \"_id\": \"5edc4abd743d11b6db08ce5a\",\n"
	 + "    \"index\": 0,\n"
	 + "    \"guid\": \"eb0e56e1-a465-4cf3-97d6-dc42d76a8e23\",\n"
	 + "    \"isActive\": false,\n"
	 + "    \"balance\": \"$1,766.72\",\n"
	 + "    \"picture\": \"http://placehold.it/32x32\",\n"
	 + "    \"age\": 22,\n"
	 + "    \"eyeColor\": \"blue\",\n"
	 + "    \"name\": \"Kent Lane\",\n"
	 + "    \"gender\": \"male\",\n"
	 + "    \"company\": \"EXPOSA\",\n"
	 + "    \"email\": \"kentlane@exposa.com\",\n"
	 + "    \"phone\": \"+1 (831) 464-2267\",\n"
	 + "    \"address\": \"941 Colonial Road, Vicksburg, New York, 7455\",\n"
	 + "    \"about\": \"Ullamco minim dolor consequat ad eu veniam voluptate proident pariatur. Aliqua tempor esse dolor esse sit aliquip commodo ipsum consequat. Consectetur nisi magna eiusmod voluptate qui.\\r\\n\",\n"
	 + "    \"registered\": \"2018-10-21T07:50:45 +04:00\",\n"
	 + "    \"latitude\": 71.975654,\n"
	 + "    \"longitude\": 74.269635,\n"
	 + "    \"tags\": [\n"
	 + "      \"dolor\",\n"
	 + "      \"ullamco\",\n"
	 + "      \"sint\",\n"
	 + "      \"commodo\",\n"
	 + "      \"ut\",\n"
	 + "      \"labore\",\n"
	 + "      \"occaecat\"\n"
	 + "    ],\n"
	 + "    \"friends\": [\n"
	 + "      {\n"
	 + "        \"id\": 0,\n"
	 + "        \"name\": \"Leonor Montoya\"\n"
	 + "      },\n"
	 + "      {\n"
	 + "        \"id\": 1,\n"
	 + "        \"name\": \"Rachelle Cantu\"\n"
	 + "      },\n"
	 + "      {\n"
	 + "        \"id\": 2,\n"
	 + "        \"name\": \"Durham Foster\"\n"
	 + "      }\n"
	 + "    ],\n"
	 + "    \"greeting\": \"Hello, Kent Lane! You have 9 unread messages.\",\n"
	 + "    \"favoriteFruit\": \"apple\"\n"
	 + "  },\n"
	 + "  {\n"
	 + "    \"_id\": \"5edc4abdd157320fd9d3ca35\",\n"
	 + "    \"index\": 1,\n"
	 + "    \"guid\": \"bcd12fd4-3067-43e2-b6ef-d6931ad74202\",\n"
	 + "    \"isActive\": false,\n"
	 + "    \"balance\": \"$3,648.68\",\n"
	 + "    \"picture\": \"http://placehold.it/32x32\",\n"
	 + "    \"age\": 28,\n"
	 + "    \"eyeColor\": \"green\",\n"
	 + "    \"name\": \"Harriett Little\",\n"
	 + "    \"gender\": \"female\",\n"
	 + "    \"company\": \"GEEKOLA\",\n"
	 + "    \"email\": \"harriettlittle@geekola.com\",\n"
	 + "    \"phone\": \"+1 (970) 443-3449\",\n"
	 + "    \"address\": \"975 Rutland Road, Gilmore, Louisiana, 6582\",\n"
	 + "    \"about\": \"Et consectetur ea culpa non qui. Irure amet et do aliquip tempor excepteur reprehenderit non duis enim elit eiusmod occaecat. Labore et deserunt laboris eiusmod non. Mollit voluptate proident exercitation consectetur anim esse mollit laborum anim id magna ea occaecat aliquip. Amet aliquip consectetur dolore anim sit culpa commodo pariatur.\\r\\n\",\n"
	 + "    \"registered\": \"2019-03-01T05:46:56 +05:00\",\n"
	 + "    \"latitude\": 30.47965,\n"
	 + "    \"longitude\": 158.419358,\n"
	 + "    \"tags\": [\n"
	 + "      \"laboris\",\n"
	 + "      \"cillum\",\n"
	 + "      \"Lorem\",\n"
	 + "      \"quis\",\n"
	 + "      \"id\",\n"
	 + "      \"in\",\n"
	 + "      \"incididunt\"\n"
	 + "    ],\n"
	 + "    \"friends\": [\n"
	 + "      {\n"
	 + "        \"id\": 0,\n"
	 + "        \"name\": \"Tabitha Hyde\"\n"
	 + "      },\n"
	 + "      {\n"
	 + "        \"id\": 1,\n"
	 + "        \"name\": \"Ferrell Strong\"\n"
	 + "      },\n"
	 + "      {\n"
	 + "        \"id\": 2,\n"
	 + "        \"name\": \"Tammy Bentley\"\n"
	 + "      }\n"
	 + "    ],\n"
	 + "    \"greeting\": \"Hello, Harriett Little! You have 6 unread messages.\",\n"
	 + "    \"favoriteFruit\": \"banana\"\n"
	 + "  },\n"
	 + "  {\n"
	 + "    \"_id\": \"5edc4abdf1f2916fa397d77f\",\n"
	 + "    \"index\": 2,\n"
	 + "    \"guid\": \"87833506-61cc-4716-a216-26c940cd1fc3\",\n"
	 + "    \"isActive\": false,\n"
	 + "    \"balance\": \"$3,343.54\",\n"
	 + "    \"picture\": \"http://placehold.it/32x32\",\n"
	 + "    \"age\": 37,\n"
	 + "    \"eyeColor\": \"blue\",\n"
	 + "    \"name\": \"Francine Owens\",\n"
	 + "    \"gender\": \"female\",\n"
	 + "    \"company\": \"KNOWLYSIS\",\n"
	 + "    \"email\": \"francineowens@knowlysis.com\",\n"
	 + "    \"phone\": \"+1 (986) 485-2057\",\n"
	 + "    \"address\": \"728 Gerald Court, Alderpoint, District Of Columbia, 1165\",\n"
	 + "    \"about\": \"Pariatur ea irure tempor occaecat occaecat dolore velit quis voluptate consectetur eiusmod magna officia ea. Ad culpa proident ipsum et Lorem sunt do do ea nostrud. Aute do fugiat labore id ad consectetur enim. Consectetur fugiat duis sint anim veniam. Sunt elit voluptate est cupidatat enim excepteur ex non ea proident amet duis. Elit ex irure exercitation do.\\r\\n\",\n"
	 + "    \"registered\": \"2018-11-08T05:53:24 +05:00\",\n"
	 + "    \"latitude\": -29.370947,\n"
	 + "    \"longitude\": -170.914026,\n"
	 + "    \"tags\": [\n"
	 + "      \"aliquip\",\n"
	 + "      \"labore\",\n"
	 + "      \"labore\",\n"
	 + "      \"laboris\",\n"
	 + "      \"et\",\n"
	 + "      \"incididunt\",\n"
	 + "      \"sint\"\n"
	 + "    ],\n"
	 + "    \"friends\": [\n"
	 + "      {\n"
	 + "        \"id\": 0,\n"
	 + "        \"name\": \"Shannon Ashley\"\n"
	 + "      },\n"
	 + "      {\n"
	 + "        \"id\": 1,\n"
	 + "        \"name\": \"Morrow Ball\"\n"
	 + "      },\n"
	 + "      {\n"
	 + "        \"id\": 2,\n"
	 + "        \"name\": \"Gross Moran\"\n"
	 + "      }\n"
	 + "    ],\n"
	 + "    \"greeting\": \"Hello, Francine Owens! You have 9 unread messages.\",\n"
	 + "    \"favoriteFruit\": \"banana\"\n"
	 + "  },\n"
	 + "  {\n"
	 + "    \"_id\": \"5edc4abdb9ae8c75e725090f\",\n"
	 + "    \"index\": 3,\n"
	 + "    \"guid\": \"4cd8a9dd-06fc-4c83-9865-378c55610028\",\n"
	 + "    \"isActive\": true,\n"
	 + "    \"balance\": \"$2,524.84\",\n"
	 + "    \"picture\": \"http://placehold.it/32x32\",\n"
	 + "    \"age\": 30,\n"
	 + "    \"eyeColor\": \"green\",\n"
	 + "    \"name\": \"George Lewis\",\n"
	 + "    \"gender\": \"male\",\n"
	 + "    \"company\": \"FLEETMIX\",\n"
	 + "    \"email\": \"georgelewis@fleetmix.com\",\n"
	 + "    \"phone\": \"+1 (895) 419-3993\",\n"
	 + "    \"address\": \"849 Oceanview Avenue, Roberts, Nebraska, 6911\",\n"
	 + "    \"about\": \"Ut elit non proident laboris magna dolore veniam magna nostrud ullamco. Fugiat reprehenderit Lorem velit laboris non anim. Sunt labore irure voluptate ipsum irure do quis.\\r\\n\",\n"
	 + "    \"registered\": \"2014-07-07T12:32:13 +04:00\",\n"
	 + "    \"latitude\": -37.494997,\n"
	 + "    \"longitude\": -127.410016,\n"
	 + "    \"tags\": [\n"
	 + "      \"eiusmod\",\n"
	 + "      \"aliquip\",\n"
	 + "      \"sunt\",\n"
	 + "      \"proident\",\n"
	 + "      \"reprehenderit\",\n"
	 + "      \"ad\",\n"
	 + "      \"non\"\n"
	 + "    ],\n"
	 + "    \"friends\": [\n"
	 + "      {\n"
	 + "        \"id\": 0,\n"
	 + "        \"name\": \"Blackwell Simmons\"\n"
	 + "      },\n"
	 + "      {\n"
	 + "        \"id\": 1,\n"
	 + "        \"name\": \"Lane Walls\"\n"
	 + "      },\n"
	 + "      {\n"
	 + "        \"id\": 2,\n"
	 + "        \"name\": \"Martha Peters\"\n"
	 + "      }\n"
	 + "    ],\n"
	 + "    \"greeting\": \"Hello, George Lewis! You have 10 unread messages.\",\n"
	 + "    \"favoriteFruit\": \"apple\"\n"
	 + "  },\n"
	 + "  {\n"
	 + "    \"_id\": \"5edc4abd22d62ce4959bae69\",\n"
	 + "    \"index\": 4,\n"
	 + "    \"guid\": \"69b9d130-4c98-4eac-91cf-9f9d36074562\",\n"
	 + "    \"isActive\": true,\n"
	 + "    \"balance\": \"$1,311.05\",\n"
	 + "    \"picture\": \"http://placehold.it/32x32\",\n"
	 + "    \"age\": 33,\n"
	 + "    \"eyeColor\": \"green\",\n"
	 + "    \"name\": \"Mcdowell Jimenez\",\n"
	 + "    \"gender\": \"male\",\n"
	 + "    \"company\": \"SQUISH\",\n"
	 + "    \"email\": \"mcdowelljimenez@squish.com\",\n"
	 + "    \"phone\": \"+1 (908) 538-2094\",\n"
	 + "    \"address\": \"168 Herkimer Court, Highland, Arizona, 6043\",\n"
	 + "    \"about\": \"Sit pariatur non adipisicing ex Lorem id proident. Veniam consectetur aliqua cillum aliquip qui et consequat ullamco aliquip ad dolore. Aute cupidatat eiusmod ea laboris pariatur mollit tempor duis qui. Sit nisi id velit voluptate sunt elit et veniam laborum deserunt duis dolore. Fugiat ipsum veniam tempor eiusmod ipsum adipisicing commodo eu. Nulla nostrud qui sunt eu consectetur enim sint eu id elit nostrud reprehenderit nisi pariatur. Laboris tempor labore do aliquip proident.\\r\\n\",\n"
	 + "    \"registered\": \"2017-04-01T05:45:53 +04:00\",\n"
	 + "    \"latitude\": -38.292611,\n"
	 + "    \"longitude\": -58.258198,\n"
	 + "    \"tags\": [\n"
	 + "      \"exercitation\",\n"
	 + "      \"pariatur\",\n"
	 + "      \"ex\",\n"
	 + "      \"laborum\",\n"
	 + "      \"pariatur\",\n"
	 + "      \"eiusmod\",\n"
	 + "      \"laboris\"\n"
	 + "    ],\n"
	 + "    \"friends\": [\n"
	 + "      {\n"
	 + "        \"id\": 0,\n"
	 + "        \"name\": \"Lori Terrell\"\n"
	 + "      },\n"
	 + "      {\n"
	 + "        \"id\": 1,\n"
	 + "        \"name\": \"Rios Mitchell\"\n"
	 + "      },\n"
	 + "      {\n"
	 + "        \"id\": 2,\n"
	 + "        \"name\": \"Holmes Hickman\"\n"
	 + "      }\n"
	 + "    ],\n"
	 + "    \"greeting\": \"Hello, Mcdowell Jimenez! You have 10 unread messages.\",\n"
	 + "    \"favoriteFruit\": \"banana\"\n"
	 + "  },\n"
	 + "  {\n"
	 + "    \"_id\": \"5edc4abd0af71ce255ab8db1\",\n"
	 + "    \"index\": 5,\n"
	 + "    \"guid\": \"7170aee1-5d8d-4939-aeb5-86cf6a58f336\",\n"
	 + "    \"isActive\": false,\n"
	 + "    \"balance\": \"$2,733.23\",\n"
	 + "    \"picture\": \"http://placehold.it/32x32\",\n"
	 + "    \"age\": 21,\n"
	 + "    \"eyeColor\": \"blue\",\n"
	 + "    \"name\": \"Benita Barnett\",\n"
	 + "    \"gender\": \"female\",\n"
	 + "    \"company\": \"ENOMEN\",\n"
	 + "    \"email\": \"benitabarnett@enomen.com\",\n"
	 + "    \"phone\": \"+1 (941) 487-2424\",\n"
	 + "    \"address\": \"653 Central Avenue, Freeburn, Kentucky, 5414\",\n"
	 + "    \"about\": \"Ullamco sunt do incididunt proident ex consequat adipisicing dolor incididunt est id quis. Sit ad sit veniam labore aliqua id ipsum magna adipisicing eiusmod minim. Veniam consectetur irure aliquip laborum ea sint dolore minim ut do id dolore minim.\\r\\n\",\n"
	 + "    \"registered\": \"2019-07-10T05:13:52 +04:00\",\n"
	 + "    \"latitude\": 70.592343,\n"
	 + "    \"longitude\": 155.505888,\n"
	 + "    \"tags\": [\n"
	 + "      \"pariatur\",\n"
	 + "      \"dolore\",\n"
	 + "      \"adipisicing\",\n"
	 + "      \"in\",\n"
	 + "      \"sit\",\n"
	 + "      \"amet\",\n"
	 + "      \"sit\"\n"
	 + "    ],\n"
	 + "    \"friends\": [\n"
	 + "      {\n"
	 + "        \"id\": 0,\n"
	 + "        \"name\": \"Karyn Huffman\"\n"
	 + "      },\n"
	 + "      {\n"
	 + "        \"id\": 1,\n"
	 + "        \"name\": \"Ladonna Jacobs\"\n"
	 + "      },\n"
	 + "      {\n"
	 + "        \"id\": 2,\n"
	 + "        \"name\": \"Kasey Stark\"\n"
	 + "      }\n"
	 + "    ],\n"
	 + "    \'greeting\': \"Hello, Benita Barnett! You have 4 unread messages.\",\n"
	 + "    \"favoriteFruit\": \"apple\"\n"
	 + "  }\n"
	 + "]";
        
        SeerStringifiedJSON JSONString = new SeerStringifiedJSON(string); //Create a stringified JSON to create the object. !STILL NEED TO ADD CHECKING
        SeerJSON JSONObject = JSONString.getJSON(); //Get the actual json object from the StringifiedJSON

        JSONObject.printObject(); //Printing origional JSON Object
		System.out.println();
		
		System.out.println(JSONObject.$(5).$("friends").$(2).$("id")); //Print out the value when used in a Print
		System.out.println(JSONObject.$(5).$("friends").$(2).$("id").getType()); //(This is going to be an int type in the form of an ESeerType Enumerator)

		System.out.println(JSONObject.$(5).$("about").<String>$()); //Get the actual return value from the object.
		
		String gettingString = JSONObject.$(5).$("about").$(); //Will actual cast if the right type (Will give an error if they are different unfortunately)
		System.out.println(gettingString);

		JSONObject.$(5).$("greeting").printObject();  //This will print out the object in its actual form. Example strings will be printed with ""
		System.out.println(JSONObject.$(5).$("greeting").getType()); //Get the ESeerType for the underlying value. (This is going to be a string as shown above.)
		
    }
}